"""
Django settings for statsapp project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-gr%#*4@3lwac+@nkh*qusz@+2s3i-r+77v&1*+e^o4x0p8g_k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = [
	'127.0.0.1'
]

# Application definition
INSTALLED_APPS = [
	'api',
	'rest_framework',
	'django.contrib.auth',
	'django.contrib.contenttypes',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'statsapp.urls'

TEMPLATES = []

WSGI_APPLICATION = 'statsapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databasesF
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'local',
		'USER': 'root',
		'PASSWORD': '',
		'HOST': 'localhost',
		'PORT': '3306',
		'OPTIONS': {
			'sql_mode': 'traditional',
		}
	}
}

## DB Cache
CACHES = {
	'default':{
		'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
		'LOCATION': 'cache',
	}
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = []

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
	'formatters': {
        'verbose': {
			'()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}]({levelname}) {message}',
			'datefmt' : '%Y-%m-%d %H:%M:%S',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'class':'logging.handlers.RotatingFileHandler',
            'filename': './logs/errors_and_debug.log',
			'formatter': 'verbose'
        },
		'console': {
            'class': 'logging.StreamHandler',
			'formatter': 'verbose'
        },
    },
    'loggers': {
		'': {
            'level': 'WARNING',
            'handlers': ['file', 'console'],
			'propagate': True,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = '/static/'

ADMIN_ENABLED = False